name: 'Update Pull Request Description on Push'
description: 'GitHub Action that updates the pull request description and title'
author: 'Yoshiya Hinosawa'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  github_token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  pr_title:
    description: 'The title of the PR'
    default: ''
  pr_body:
    description: 'The body of the PR'
    default: ''
  destination_branch:
    description: 'Base branch of the PR. Default is master.'
    default: master
  source_branch:
    description: 'Source branch'
branding:
  icon: git-pull-request
  color: green
